### ISSUE TITLE
Alternative to tab panel in widget?

### ISSUE THREAD

**Issue by j-andrews7** [ebi-gene-expression-group/atlas-heatmap#10]
On the web page, there is a panel on the left side (at least for homo sapiens), that let's you display different groups of experiments, like cell lines, diseases, etc. Is there a way to specify multiple experiments for display in the widget?

**Comment by j-andrews7** [comment]
I've come across the npm package for the [experiment page](https://www.npmjs.com/package/expression-atlas-experiment-page), but it's not really clear how it can be utilized. 

As an aside, the widget works quite well in Electron applications as well.

**Comment by alfonsomunozpomer** [comment]
Hi, currently such functionality isn’t supported by the widget. However, the React component that shows the left sidebar and uses the heatmap is here: https://github.com/ebi-gene-expression-group/atlas/tree/dev/gxa/src/main/javascript/atlas_bundles/baseline-expression

Unfortunately it’s one of the oldest parts of the project and there are certain conventions and ES idioms which are somewhat outdated (we don’t use `jsx` extensions anymore, we made our own crude router instead of using ReactRouter, there are no tests to be found, we parse URLs without any libraries...). Still, we’ll be very curious if this somehow helped or if you could package it in its own SPA.

HTH.

**Comment by j-andrews7** [comment]
It's good to know it exists, but I have thus far avoided React in this project and it would likely require a pretty good amount of work (and learning on my part) to incorporate it properly. 

A follow-up question though: is there anyway to programmatically retrieve lists of all experiments for a given organism? Or just a flat list of all the experiments (names & indentifiers) somewhere that I can download?

**Comment by alfonsomunozpomer** [comment]
Sure thing:
https://www.ebi.ac.uk/gxa/json/experiments

**Comment by j-andrews7** [comment]
That is perfect, thank you. I'm going to close this since my question has been answered.

**Comment by alfonsomunozpomer** [comment]
Thank you and don’t hesitate to get in touch with us again should you need anything. May I ask where are you integrating the widget?

There is also a [mailing list, atlas-widget@ebi.ac.uk](https://listserver.ebi.ac.uk/mailman/listinfo/atlas-widget), where we announce new releases of the widget and we advise of breaking changes (if any), test releases, etc. It’s very low traffic (you won’t get more than a couple of emails per month), and you’re more than welcome to join if you want.

**Comment by j-andrews7** [comment]
Sure - it's an Electron app called [Genotify](https://github.com/j-andrews7/GenotifyDesktop) for quick gene lookup & summarization that integrates information from multiple databases through their APIs. Works for pretty much any species, is cross-platform, and easier than futzing with constantly Googling things when searching lists from -omics results or doing a lit review. In theory, anyway. 

I haven't made the binaries yet for the latest release, but the master branch in the repo is up to date if you have any desire to see it in action and have node.js installed.

I wanted a way to integrate expression data and your widget was by far the best solution, so thanks for it! We plan to submit the paper for Genotify in the next week or two.

**Comment by alfonsomunozpomer** [comment]
I just cloned it and played quickly with it. Looks good and definitely it’ll be useful to have comprehensive information about a gene in a single place. I’m happy to see that the widget integrates nicely with an Electron app (no reason why it shouldn’t), but it’s the first use case we’ve had in a desktop app.

**Comment by j-andrews7** [comment]
ProtVista is actually exactly what I felt I was missing! JBrowse needs too
much backend data, but the ProtVista widget should work perfectly.
Hopefully I will include it in the next release. Thanks for the tip.
