### ISSUE TITLE
Building from source: docs?

### ISSUE THREAD

**Issue by yochannah** [ebi-gene-expression-group/atlas-heatmap#6]
Hi,

I'd like to build this gorgeous heatmap from source to include as a visualisation for genes in bluegenes ([source](https://github.com/intermine/bluegenes), [demo](http://bluegenes.apps.intermine.org/).

after cloning the code, what's the easiest way to generate the bundle files?

**Comment by wbazant** [comment]
Heya! Would you not prefer to install us through npm? See the package.json for the package name. Npm install expression-atlas-heatmap-highcharts.

If you want the bundles, I guess you want to fork the heatmap and not use it as a component? If so, clone the code,` npm install` and `webpack ` (or see in package.json which npm command will do building).

**Comment by yochannah** [comment]
hmmm, let me explain my use case a little more clearly. Our plan for BlueGenes is to include a number of nice javascript visualisation tools in report pages for genes, proteins, etc. In order to do so, each we'll probably need to create a bundle of some sort containing the code for the visualisation tool, including its css and some extra bluegenes script bits to allow the tool to initialise dynamically from bluegenes. 

I initially tried the npm install route, but I couldn't see the bootstrap override stylesheet, which I think I would need? Hence why I tried to clone instead.

Let me know if that makes sense? We really think this expression visualiser is a great tool, by the way!

**Comment by wbazant** [comment]
We're glad you like it! Would it work for you to include the css as hosted from us? If so, add the line with the stylesheet that's in the readme to the html page you are serving, not through the bundler. If it's clashing with your own css you can later put our heatmap in an iframe if you need to, let us know if that's the case! 

I think if you add that link, and npm install us, everything will work. We can put the css into an npm package (and people will have to require() it in their javascript, or else we won't allow them to use their own bootstrap ) but there wasnt a need so far.

What technology stack are you using for your project?

**Comment by yochannah** [comment]
I think we'd probably rather include the css in our bundle rather than as an externally served dependency. Part of the eventual BlueGenes tool build process I'm setting up will hopefully involve running external css through a quick preprocessor build to sandbox external css files. 

Having the css in the repo itself would nice, with all the parts of the tool nicely encapsulated in the same place, but I don't want to inconvenience you and your users. If it's not likely to change much I could just add a static copy to our repo. That might be easiest, rather than asking you to change things?

BlueGenes is Clojure (server) and ClojureScript (clientside, compiles to JS) based, but the bluegenes tool framework will accept anything that is natively css/js or compiles to js/css.

**Comment by wbazant** [comment]
Wholesome! We transpile to javascript before publishing to npm (npm install and peek what's in the lib folder) so it should all work. 

We wouldn't want to be tied up to a css file either -
 for now just put a copy of customized-bootstrao.css in your repo and npm install the package. Let's keep this issue open, we'll think of a long term solution with @alfonsomunozpomer.

**Comment by yochannah** [comment]
sounds like a plan. Thanks for your help talking it through! :)

**Comment by alfonsomunozpomer** [comment]
Hi @yochannah, I’d like to know if you managed to build the heatmap in your application. Could you give us a status update?

**Comment by yochannah** [comment]
Hey @alfonsomunozpomer! I had to put the project to the side for a bit; but I will be coming back to it soon. I'll update with details when I have them!

**Comment by alfonsomunozpomer** [comment]
Since I haven’t seen any activity in the last months I’m closing this issue. Feel free to reopen it if you need any help.
